### ISSUE TITLE
Thank

### ISSUE THREAD

**Issue by LordVenom** [duc010298-1/translate-renpy#3]
Thank you for this tool, just an improvement of the visual interface or at least modifiable variables to launch it directly from a python editor.
Also as you use the browser, the Deepl translator would be perfect.

**Comment by duc010298-1** [comment]
> Thank you for this tool, just an improvement of the visual interface or at least modifiable variables to launch it directly from a python editor.

Thanks for your review, I am also looking into implementing a version of this tool with the GUI. Of course, for the end user, the GUI is always easy.


> Also as you use the browser, the Deepl translator would be perfect.

I looked through Deepl, it still has some restrictions like language limit and Character limit (with free account). If you have to pay fees to get unlimited characters, then using Google translate API will be more efficient.

Of course, using Google Translate with Selenium is not perfect. Google will block access and you will not be able to translate any characters if they realize you are acting abnormally, this only happens if you run the tool with too many threads (open so many browser tabs to translating)
